//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeraçãoUnidades.Unidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidades
    {
        public int Id { get; set; }
        public string SECRETARIA { get; set; }
        public string AGRUPAMENTO { get; set; }
        public string SUBPREFEITURA { get; set; }
        public string ADMREGIONAL { get; set; }
        public string DRE { get; set; }
        public string TIPOUNIDADE { get; set; }
        public string Nome { get; set; }
        public string CODUND { get; set; }
        public string NOMEUNIDADE { get; set; }
        public string ENDEREÇO { get; set; }
        public string TELEFONE { get; set; }
        public string CEP { get; set; }
        public string BAIRRO { get; set; }
        public string INICIOCONVENIO { get; set; }
        public string FIMCONVENIO { get; set; }
        public string TIPOATENDIMENTO { get; set; }
        public string INICIODESATIVACAO { get; set; }
        public string FIMDESATIVACAO { get; set; }
        public string CODIGOEOL { get; set; }
        public string INAUGURADO { get; set; }
        public string INICIOTIPOATENDIMENTO { get; set; }
        public string FIMTIPOATENDIMENTO { get; set; }
    }
}
